steps:

  - id: "Executando teste unitario"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['go', 'test', 'soma']
    env: ['GOPATH=.']

  - id: "Compilando app"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['go', 'build', '-ldflags="-s -w"', 'soma']
    env: ['GOPATH=.']

  - id: "Gerando imagem"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/golang-ci:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/golang-ci:latest'

tags: ['cloud-builders-golang-ci']
